tap "oven-sh/bun"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Cross-shell prompt for astronauts
brew "starship"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one.
brew "oven-sh/bun/bun", trusted: true
# Distribution of the Python and R programming languages for scientific computing
cask "anaconda"
cask "font-blex-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-lxgw-wenkai"
cask "font-meslo-lg-nerd-font"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
npm "@bytedance-dev/bytedcli"
npm "@larksuite/cli"
npm "@openai/codex"
npm "pyright"
